@startuml
class サイリウムライト {
  - 点灯状態
  + 点灯する()
  + 消灯する()
}

class 点灯状態 {
  + 青
  + 赤
  + 消灯
}

note top of サイリウムライト {
  点灯状態はどうする？
}

note top of サイリウムライト {
  点灯パターンクラスというものにロジックを、
  埋めたほうがよいかもしれないが、
  現在は単純なので、
  サイリウムライトに持っていることにする
}

@enduml
