@startuml

left to right direction

actor ユーザ as user 

rectangle {
    usecase "ライトの点灯する" as lightUp
    usecase "ライトの色を変える" as change
    usecase "ライトの消灯する" as lightOff

    user --> lightUp
    user --> change
    user --> lightOff
}


@enduml
