@startuml

title "券売機モデル"


actor "利用者" as user

agent kenbaiki as "
券売機
--
きっぷ
お金
"
agent ticket as "
きっぷ
--
価格
区間
"
agent "お金" as money

user -right---> kenbaiki : お金を投入する
' user -right---> money : 所持
kenbaiki -left-> user : きっぷを発券する

user *-- money
kenbaiki *-- money
user *-- ticket
kenbaiki *-- ticket


@enduml